// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTiPQwwCZmMnuwJk8y_86ZexZQesdZaVs',
    appId: '1:812720331101:android:1b476aa499aefd9b95b0b4',
    messagingSenderId: '812720331101',
    projectId: 'chore-flick',
    storageBucket: 'chore-flick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZuZIcq7bj8AvyESsHuxTfRPIIAfnZ6Yg',
    appId: '1:812720331101:ios:831305ddf78aa76995b0b4',
    messagingSenderId: '812720331101',
    projectId: 'chore-flick',
    storageBucket: 'chore-flick.firebasestorage.app',
    androidClientId: '812720331101-2fg6h3j9ig8p87qddtbje0rudijh4199.apps.googleusercontent.com',
    iosClientId: '812720331101-pn93chqa5sa038n5nild1j3lb353ruil.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

}